async page => {
  const check = (condition, message) => { if (!condition) throw new Error(message); };
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.reload();
  await page.getByRole('status').filter({hasText:'21 reactions'}).waitFor();
  check(await page.locator('.card').count() === 21, 'All 21 reactions render');
  const search = page.getByRole('searchbox', {name:'Search reactions'});
  await search.fill('cats');
  check(await page.locator('.card').count() === 7, 'Plural cat search');
  await search.fill('thumbs up');
  check(await page.locator('.card').count() === 3, 'Multi-word gesture search');
  await search.fill('no-such-animal-123');
  check(await page.getByText('No matching moods.').isVisible(), 'Empty state');
  await page.getByRole('button',{name:'Clear search'}).click();
  await page.getByRole('button',{name:'Peace',exact:true}).click();
  check(await page.locator('.card').count() === 2, 'Mood filter');
  await page.reload();
  await page.getByRole('status').filter({hasText:'2 reactions'}).waitFor();
  await page.getByRole('button',{name:'All',exact:true}).click();
  await page.getByRole('button',{name:'View very chill',exact:true}).click();
  check(await page.getByRole('dialog').isVisible(),'Preview opens');
  await page.locator('#detail-image').evaluate(img=>img.decode());
  await page.context().grantPermissions(['clipboard-read','clipboard-write']);
  await page.getByRole('button',{name:'Copy image link'}).click();
  await page.getByText('Link copied',{exact:true}).waitFor();
  const copied = await page.evaluate(()=>navigator.clipboard.readText());
  check(copied.endsWith('/images/chill-cat.jpg'),'Image link copied');
  const downloadPromise=page.waitForEvent('download');
  await page.getByRole('link',{name:'Download',exact:true}).click();
  const download=await downloadPromise;
  check(download.suggestedFilename()==='chill-cat.jpg','Download filename');
  check(await download.failure()===null,'Download succeeds');
  await page.screenshot({path:'output/detail.png'});
  await page.keyboard.press('Escape');
  check(!await page.getByRole('dialog').isVisible(),'Escape dismisses preview');
  await page.setViewportSize({width:390,height:844});
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No mobile horizontal overflow');
  await page.screenshot({path:'output/mobile-final.png'});
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:'output/desktop-final.png'});
  check(errors.length===0, errors.join('\n'));
  return 'Passed: 21 images, search, plural search, gesture search, empty state, filters, URL persistence, preview, clipboard, download, Escape, mobile layout; no page errors.';
}
