async page => {
  const check = (condition, message) => { if (!condition) throw new Error(message); };
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.reload();
  await page.waitForFunction(() => document.querySelectorAll('.card').length === 243);
  check((await page.locator('body').innerText()).trim() === 'reacts', 'No unnecessary gallery copy');
  const search = page.getByRole('searchbox', {name:'Search reactions'});
  await search.fill('cats');
  check(await page.locator('.card').count() === 140, 'Plural cat search');
  await search.fill('dork');
  check(await page.locator('.card').count() === 8, 'Eight Dork scenes searchable');
  await search.fill('mtg');
  check(await page.locator('.card').count() === 15, 'Magic scenes searchable');
  await search.fill('lean cup');
  check(await page.locator('.card').count() === 8, 'New cup images searchable');
  await page.reload();
  await page.waitForFunction(() => document.querySelectorAll('.card').length === 8);
  await search.fill('smoking');
  check(await page.locator('.card').count() === 10, 'New smoking images searchable');
  await search.fill('duo');
  check(await page.locator('.card').count() === 41, 'All duo scenes searchable');
  await page.getByRole('button',{name:'View did you hear that',exact:true}).click();
  await page.locator('#detail-image').evaluate(img=>img.decode());
  await page.keyboard.press('Escape');
  await search.fill('trio');
  check(await page.locator('.card').count() === 10, 'Ten new trios searchable');
  await page.getByRole('button',{name:'View committee meeting',exact:true}).click();
  await page.locator('#detail-image').evaluate(img=>img.decode());
  await page.keyboard.press('Escape');
  await search.fill('no-such-animal-123');
  check(await page.getByText('No results.',{exact:true}).isVisible(), 'Empty state');
  await search.fill('');
  await page.getByRole('button',{name:'View dork approves',exact:true}).click();
  check(await page.getByRole('dialog').isVisible(),'Preview opens');
  await page.locator('#detail-image').evaluate(img=>img.decode());
  await page.context().grantPermissions(['clipboard-read','clipboard-write']);
  await page.getByRole('button',{name:'copy link',exact:true}).click();
  await page.getByRole('button',{name:'copied',exact:true}).waitFor();
  check((await page.evaluate(()=>navigator.clipboard.readText())).endsWith('/images/dork-approves.jpg'),'Image link copied');
  const downloadPromise=page.waitForEvent('download');
  await page.getByRole('link',{name:'download',exact:true}).click();
  const download=await downloadPromise;
  check(download.suggestedFilename()==='dork-approves.jpg','Download filename');
  check(await download.failure()===null,'Download succeeds');
  await page.screenshot({path:'output/detail.png'});
  await page.keyboard.press('Escape');
  check(!await page.getByRole('dialog').isVisible(),'Escape dismisses preview');
  await page.setViewportSize({width:390,height:844});
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No mobile horizontal overflow');
  await page.screenshot({path:'output/mobile.png'});
  await page.setViewportSize({width:1280,height:900});
  await page.emulateMedia({colorScheme:'dark'});
  await page.screenshot({path:'output/dark.png'});
  await page.emulateMedia({colorScheme:'light'});
  await page.screenshot({path:'output/desktop.png'});
  check(errors.length===0, errors.join('\n'));
  return 'Passed: 243 images, minimal copy, search, new image tags, empty state, URL persistence, preview, clipboard, download, Escape, mobile layout and both themes; no page errors.';
}

